# Generated by Django 5.0.1 on 2024-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('accountingId', models.AutoField(primary_key=True, serialize=False)),
                ('accountingName', models.CharField(max_length=50)),
                ('spend', models.IntegerField()),
                ('consumeType', models.CharField(max_length=2)),
                ('assetType', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transactionDate', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('available', models.CharField(max_length=1)),
                ('createdId', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting',
            },
        ),
    ]
