# Generated by Django 5.0.1 on 2024-10-08 15:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('avatar_path', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='avatars/')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=20, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
                ('ca_path', models.FileField(default=None, max_length=250, null=True, upload_to='ca_file/')),
                ('ca_passwd', models.CharField(max_length=255)),
                ('person_id', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_credentials',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_successful', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='ConsumeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('createdId', models.ForeignKey(db_column='createdId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consume_type',
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountingName', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('assetType', models.CharField(choices=[('0', '收入'), ('1', '支出')], default='0', max_length=20)),
                ('transactionDate', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdId', models.ForeignKey(db_column='createdId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accountType', models.ForeignKey(db_column='accountType', on_delete=django.db.models.deletion.CASCADE, to='backend.accounttype')),
                ('consumeType', models.ForeignKey(db_column='consumeType', on_delete=django.db.models.deletion.CASCADE, to='backend.consumetype')),
            ],
            options={
                'db_table': 'accounting',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_portfolio',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='backend.investmentportfolio')),
            ],
            options={
                'db_table': 'investment',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuthRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_auth_record',
            },
        ),
    ]
