# Generated by Django 5.0.1 on 2024-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
