# Generated by Django 5.0.1 on 2024-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='createdId',
            field=models.CharField(max_length=150),
        ),
    ]
