# Generated by Django 5.0.1 on 2024-04-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeType',
            fields=[
                ('consumeTypeId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('icon', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('available', models.CharField(max_length=1)),
                ('createdId', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consume_type',
            },
        ),
        migrations.AlterField(
            model_name='accounting',
            name='consumeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consumetype'),
        ),
    ]
