# Generated by Django 5.0.1 on 2024-10-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_budget_is_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='username',
        ),
    ]
