# Generated by Django 5.0.1 on 2024-05-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_accounting_createdid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='consumeType',
            new_name='consumeType_id',
        ),
    ]
