# Generated by Django 5.0.1 on 2024-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_consumetype_alter_accounting_consumetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consumetype',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
