# Generated by Django 5.0.1 on 2024-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_consumetype_accounting_consumetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='ca_passwd',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apicredentials',
            name='ca_path',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apicredentials',
            name='person_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
