# Generated by Django 5.0.1 on 2024-10-09 12:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_user_budget_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
