# Generated by Django 5.0.1 on 2024-05-22 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_apicredentials_ca_passwd_apicredentials_ca_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
