# Generated by Django 5.0.1 on 2024-05-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_asset_date_added_liability_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
