# Generated by Django 5.0.1 on 2024-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_defaultinvestmentportfolio_defaultinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultinvestmentportfolio',
            name='available',
        ),
        migrations.RemoveField(
            model_name='defaultinvestmentportfolio',
            name='description',
        ),
        migrations.AlterField(
            model_name='defaultinvestmentportfolio',
            name='investment_threshold',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='DefaultInvestment',
        ),
    ]
