# Generated by Django 5.0.1 on 2024-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
