# Generated by Django 5.0.1 on 2024-10-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_defaultinvestmentportfolio_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='backend.defaultinvestmentportfolio')),
            ],
            options={
                'db_table': 'Default_Stock_List',
            },
        ),
    ]
