# Generated by Django 5.0.1 on 2024-09-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='type',
        ),
        migrations.AlterField(
            model_name='investment',
            name='shares',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='investment',
            table=None,
        ),
    ]
