# Generated by Django 5.0.1 on 2024-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_defaultstocklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultStockList',
        ),
    ]
