# Generated by Django 5.0.1 on 2024-09-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_investment_type_alter_investment_shares_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investment',
            table='investment',
        ),
    ]
