# Generated by Django 5.0.1 on 2024-10-05 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_investment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_path',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='TwoFactorAuthRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_auth_record',
            },
        ),
    ]
