# Generated by Django 5.0.1 on 2024-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_defaultstocklist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolio',
            name='quota',
            field=models.IntegerField(null=True),
        ),
    ]
