# Generated by Django 5.0.1 on 2024-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_investmentportfolio_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='buyType',
            field=models.CharField(choices=[('0', 'buy and hold'), ('1', 'naive'), ('2', 'custom')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='assetType',
            field=models.CharField(choices=[('0', '收入'), ('1', '支出')], default='0', max_length=1),
        ),
    ]
