# Generated by Django 5.0.1 on 2024-10-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_investment_buytype_alter_accounting_assettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='buyType',
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='buyType',
            field=models.CharField(choices=[('0', 'buy and hold'), ('1', 'naive'), ('2', 'custom')], default='0', max_length=1),
        ),
    ]
