# Generated by Django 5.0.1 on 2024-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='generated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
