services:
  backend:
    build:
      context: .
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
