events {
    worker_connections 1024;
}

http {
    # HTTPS 配置
    server {
        listen 443 ssl;
        server_name www.zhitoujinfang.website;  # 替換為您的實際域名

        # SSL 憑證設置
        ssl_certificate /etc/ssl/certs/server-cert.pem;  # 伺服器憑證
        ssl_certificate_key /etc/ssl/private/server-key.pem;  # 伺服器私鑰

        # SSL 設定（可以根據需要進行調整）
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';

        # 預設 / 的處理，轉發到 React 前端
        location / {
            proxy_pass http://140.131.114.159:3000;  # 將請求轉發到 React 前端容器的 3000 端口
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # CORS 配置
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";

            # 處理 OPTIONS 預檢請求
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
                add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                return 204;
            }
        }

        # 新增 /backend 路徑的配置，轉發到後端服務（例如：8000 端口）
        location /backend/ {
            #rewrite ^/backend/(.*)$ /$2 break;
            proxy_pass http://140.131.114.159:8000/;  # 將請求轉發到本機的 8000 端口，這是後端服務
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 其他 CORS 或其他設定（根據需求可選）
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
        }
    }
}